# This file was generated by GoReleaser. DO NOT EDIT.
class Monkey < Formula
  desc "https://github.com/bradford-hamilton/monkey-lang."
  homepage ""
  version "0.2.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradford-hamilton/monkey-lang/releases/download/v0.2.5/monkey-lang_0.2.5_Darwin_x86_64.tar.gz"
    sha256 "adc6153b276fc427d3e91b75ace5b093f1660db4cf4bf5e32f59ae7821dcf153"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bradford-hamilton/monkey-lang/releases/download/v0.2.5/monkey-lang_0.2.5_Linux_x86_64.tar.gz"
      sha256 "b8c2ca66ba11d8218811cf4f5165580e1e5980d2743d2cfc8868507889a7d0d0"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "monkey"
  end
end
