# This file was generated by GoReleaser. DO NOT EDIT.
class Monkey < Formula
  desc "https://github.com/bradford-hamilton/monkey-lang."
  homepage ""
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradford-hamilton/monkey-lang/releases/download/v0.2.1/monkey-lang_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "04ae922bb9348847aaf9846b5805a0383f6c0504dcffc918a470f8efa27e1a59"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bradford-hamilton/monkey-lang/releases/download/v0.2.1/monkey-lang_0.2.1_Linux_x86_64.tar.gz"
      sha256 "881ca1c970351dc9c9ab1d6b4e6c27f0154889ef846a253251d2520baa2746b1"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "monkey"
  end
end
