# This file was generated by GoReleaser. DO NOT EDIT.
class Monkey < Formula
  desc "https://github.com/bradford-hamilton/monkey-lang."
  homepage ""
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradford-hamilton/monkey-lang/releases/download/v0.3.0/monkey-lang_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "c28d52e0105dc64a0ed2ed5a08701314a391fba88784fdfbcf8b8332ce6922be"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bradford-hamilton/monkey-lang/releases/download/v0.3.0/monkey-lang_0.3.0_Linux_x86_64.tar.gz"
      sha256 "2a19876f62050707bd84b33dc3077484273feb0401cca7ac8c8ac7d655b2ad23"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "monkey"
  end
end
